language: node_js
dist: trusty
sudo: required
node_js: 6
script:
- npm run test
cache:
  directories:
  - node_modules
env:
  global:
  - CF_APP=electrolux-source
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=rishacha@in.ibm.com
  - CF_SPACE=dev
  - CF_PASSWORD=c^thY@1969
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
  - cf-blue-green-travis
  on:
    branch: master
    repo: bassdeveloper/Electrolux-Demo
  skip_cleanup: true
