language: node_js
dist: trusty
sudo: required
node_js: 6
script:
- npm run test
cache:
  directories:
  - node_modules
env:
  global:
  - CF_APP=electrolux-source
  - CF_USERNAME=rishacha@in.ibm.com
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=rishacha@in.ibm.com
  - CF_SPACE=dev
  - secure: mkLPqqzPws2Xc5eBrAcDt+bZwPsHw7/7yy2en7mALMxjrcAvLAJIM5KFQp0qfXByrS1TUu4/n9HFPTH4GCPP5zSvfxOXUTmBHeaU35owNIZZfPl9DKyE6qGTGrYx7lv8TG/6MhGCDotEY4oDr8LIWeNsE7jsoqThOCTSqe66cFrgKEU6eJd2q6LuRrVrMYd8Eje2AfSLuwkT6moVXJ2plyYBjIGUQaPrZOU69N6FdyMQz+o4jBjMkkIKCA5sQU7yTEwgZdmJPO/3VJfBDCajHWnvpnvtEapyVeHMagwliKq69ZxOU2+9KPS986DwE/3sZSoHSqV2MLQ5iIwF4Mwt1Yq+usNQYKUPhGFQh6d4wSDlOvaPDrgeXZnMYNdghuI3phusyw/qjeTr2nRZ2dXz3PpcFDgUKUx9noti7Mh6CzesiTG31jp1JyVCkPKAENheT56R0XXjeSZx4dEWIkywMtwgHB36kjBBytAQtZAL/AGVEZljnZ8uARGaA0ITm6rjytwui8IDzqH/Zhve6mmmpqR0zflbvsvWolUXMcawQVBkoN6Dtby01z8EiISyF983mXqfWjIit7C45QJ9sQt8fvlYrevXa2iRsqPtRfY8Bef1Xd3lYMl3gxQurgPtdeI23RDWymf0JpZrJyTMA/1cDtL7yVn1JSIuIBrzW5VUDr4=
